import { mapWithConcurrency } from "./concurrency";
import type { DecisionMaker } from "./decisions";
import { hasMovedAway, illnessIdsSubsumedByDeath } from "./events";
import { DREAM_GOALS, dreamGerund, type DreamGoal, type Memory, type PersonMind, type Thought } from "./mind";
import { keyedDraw, keyedRng } from "./rng";
import { DEATH_CAUSE_PHRASE, type DeathCause } from "./mortality";
import { LANDMARK_POOL, pickLandmarkFor, pickLandmarks, seasonFor, type Landmark } from "./town";
import type { Event, Person } from "./types";

/** Landmarks plausible as a place two people would meet — a subset of the town's full landmark set (round 5, decision 026). */
const MEETING_FRIENDLY: ReadonlySet<Landmark> = new Set(["the fairground", "the market square", "the chapel", "the old well"]);

function meetingPlaceFor(seed: string, townName: string, key: string, year: number): Landmark | undefined {
  const candidates = pickLandmarks(seed, townName, LANDMARK_POOL.length).filter((l) => MEETING_FRIENDLY.has(l));
  if (candidates.length === 0) return undefined;
  const rng = keyedRng(seed, key, year, "meeting-place");
  return candidates[Math.floor(rng() * candidates.length)];
}

/**
 * Prose is rendered FROM events by templates — never generated by an LLM
 * and never stored. This is the only place strings get assembled for
 * display; everything else in the domain deals with structured events.
 *
 * Each kind has 2-3 phrasings, picked by a keyed RNG draw (namespaced
 * `narrate:<kind>` so it never collides with a simulation decision's RNG
 * key) so the choice is deterministic and stable across renders, but the
 * chronicle doesn't repeat the exact same sentence shape for every
 * marriage in town.
 */
function name(people: Readonly<Record<string, Person>>, id: string | undefined): string {
  if (!id) return "someone";
  return people[id]?.name ?? id;
}

function pick<T>(seed: string, event: Event, variants: readonly T[]): T {
  if (variants.length === 1) return variants[0]!;
  const key = event.actors.join("-") || event.id;
  const draw = keyedDraw(seed, key, event.year, `narrate:${event.kind}`);
  return variants[Math.floor(draw * variants.length)]!;
}

export function narrateEvent(event: Event, people: Readonly<Record<string, Person>>, seed = "narrate", townName = "town", allEvents: readonly Event[] = []): string {
  const [a, b] = event.actors;
  const A = name(people, a);
  const B = name(people, b);

  switch (event.kind) {
    case "birth": {
      // Concrete world texture (round 5 pivot, decision 026): a season is purely atmospheric
      // (a deterministic keyed pick, never claimed as having caused anything). A same-year
      // hardship town event is different — it's a REAL simulated event (`allEvents`, passed in
      // by the caller), so referencing it is a real causal coincidence, not invented color —
      // matching the handoff's "born during the winter storm that destroys the northern bridge".
      const season = seasonFor(seed, event.actors.join("-") || event.id, event.year, "birth");
      const sameYearTown = allEvents.find((e) => e.kind === "town" && e.year === event.year && typeof e.payload.eventType === "string");
      if (sameYearTown) {
        const eventType = String(sameYearTown.payload.eventType);
        const landmarks = pickLandmarks(seed, townName);
        const landmark = eventType === "fire" ? pickLandmarkFor(seed, "world", event.year, landmarks) : undefined;
        const hardshipPhrase = landmark ? `the ${eventType} that damaged ${landmark}` : `the ${eventType} that struck ${townName} that year`;
        return `${A} was born to ${B} and ${name(people, event.actors[2])}, during ${hardshipPhrase}.`;
      }
      return pick(seed, event, [
        `${A} was born to ${B} and ${name(people, event.actors[2])}, during ${season} of ${event.year}.`,
        `${B} and ${name(people, event.actors[2])} welcomed a child, ${A}, in ${season}.`,
      ]);
    }
    case "school":
      return `${A} started school.`;
    case "job": {
      if (event.payload.forced) return `${A} took up work as ${withArticle(String(event.payload.job))}.`;
      // Round 6 fix (decision 028, "let the prose explain" career changes): a real career CHANGE
      // (not the person's first job) names the years they spent at the old trade, using the
      // previous `job` event on the SAME person's own log — real tenure, not an invented number.
      const priorJob = allEvents
        .filter((e) => e.kind === "job" && e.actors[0] === a && e.year < event.year)
        .sort((x, y) => y.year - x.year)[0];
      if (priorJob) {
        const years = event.year - priorJob.year;
        return `After ${years} year${years === 1 ? "" : "s"} as ${withArticle(String(priorJob.payload.job))}, ${A} became ${withArticle(String(event.payload.job))}.`;
      }
      return pick(seed, event, [`${A} became ${withArticle(String(event.payload.job))}.`, `${A} took up the trade of ${String(event.payload.job)}.`]);
    }
    case "move":
      if (event.payload.arrived) return pick(seed, event, [`${A} arrived in town and settled in.`, `${A} came to town looking for a new start.`]);
      if (event.payload.forced) return `${A} left for ${String(event.payload.destination ?? "parts unknown")}.`;
      return pick(seed, event, [
        `${A} moved away to ${String(event.payload.destination ?? "parts unknown")}.`,
        `${A} packed up and left for ${String(event.payload.destination ?? "parts unknown")}.`,
      ]);
    case "romance": {
      const key = event.actors.join("-") || event.id;
      const season = seasonFor(seed, key, event.year, "romance");
      const place = meetingPlaceFor(seed, townName, key, event.year);
      const placePhrase = place ? ` at ${place}` : "";
      return pick(seed, event, [`${A} met ${B}${placePhrase} during ${season}, and they began courting.`, `${A} and ${B} started courting, having met${placePhrase} in ${season}.`]);
    }
    case "marriage":
      if (event.payload.forced) return `${A} and ${B} were married.`;
      return pick(seed, event, [`${A} married ${B}.`, `${A} and ${B} were wed.`]);
    case "breakup":
      if (event.payload.blocked) return `${A} and ${B} never got the chance to marry, and drifted apart.`;
      return pick(seed, event, [`${A} and ${B} broke up.`, `${A} and ${B}'s courtship ended.`]);
    case "feud":
      // `escalated` (set by the A6 "sabotage" outcome, simulate.ts) means this is NOT the feud's
      // opening move but another round of an already-ongoing one — must read differently, or a
      // years-long feud reads as "began a bitter feud" over and over (round 4 fix, decision 021).
      if (event.payload.escalated) return pick(seed, event, [`${A} struck back at ${B}, and the feud deepened.`, `${A} escalated the feud with ${B} further.`]);
      return pick(seed, event, [`${A} and ${B} began a bitter feud.`, `A bitter feud broke out between ${A} and ${B}.`]);
    case "reconciliation":
      return pick(seed, event, [`${A} and ${B} reconciled.`, `${A} and ${B} made peace at last.`]);
    case "illness":
      if (event.payload.recovered) return pick(seed, event, [`${A} fell ill, but recovered.`, `${A} took ill for a time, then recovered.`]);
      return `${A} fell ill.`;
    case "death": {
      const causeCode = typeof event.payload.cause === "string" ? event.payload.cause : undefined;
      const causePhrase = causeCode && causeCode in DEATH_CAUSE_PHRASE ? DEATH_CAUSE_PHRASE[causeCode as DeathCause] : undefined;
      if (event.payload.awayFromTown) return `Word reached town that ${A} had died elsewhere, at age ${String(event.payload.age)}.`;
      if (causePhrase) return pick(seed, event, [`${A} died of ${causePhrase} at age ${String(event.payload.age)}.`, `${A} was taken by ${causePhrase}, at age ${String(event.payload.age)}.`]);
      return pick(seed, event, [`${A} died at age ${String(event.payload.age)}.`, `${A} passed away at age ${String(event.payload.age)}.`]);
    }
    case "child":
      return `${A} and ${B} decided to have a child.`;
    case "breakdown": {
      const breakdownKind = String(event.payload.kind ?? "a breaking point");
      const response = event.payload.response;
      if (response === "master-it") return `${A} was pushed to the brink (${breakdownKind}), and mastered it.`;
      return `${A} broke down under the weight of it all (${breakdownKind}).`;
    }
    case "dream": {
      // Round 5 grammar fix (decision 023): `event.payload.goal` is the raw, imperative-ish
      // DreamGoal string ("leave for the city"), kept raw because it's also read back
      // programmatically (`dreamGoalSatisfiedBy` in simulate.ts); only rendering goes through
      // `dreamGerund` to avoid "dreamed of leave for the city".
      const rawGoal = event.payload.goal;
      const goal = typeof rawGoal === "string" && (DREAM_GOALS as readonly string[]).includes(rawGoal) ? dreamGerund(rawGoal as DreamGoal) : String(rawGoal ?? "their dream");
      // Round 7 fix (decision 030): a real pronoun ("her sights"/"his sights"), not singular
      // "their" — sex is always known for a real person. Falls back to "their" only if the actor
      // somehow isn't resolvable (never happens for a real "dream" event, defensive only).
      const dreamer = a ? people[a] : undefined;
      const pronoun = dreamer ? possessiveLower(dreamer.sex) : "their";
      if (event.payload.outcome === "realized") return `${A} dreamed of ${goal}, and this dream was realized in ${event.year}.`;
      if (event.payload.outcome === "abandoned") return `${A} let go of ${pronoun} dream of ${goal}.`;
      // Round 7 fix (decision 030, "dream churn is noise"): a dream change now always names WHY
      // (`payload.cause`, set by simulate.ts's A8 "adjust-it" branch — `adjust-it` is only ever
      // offered when there's a real cause, see decision 030) instead of just announcing a new one.
      const cause = typeof event.payload.cause === "string" ? event.payload.cause : undefined;
      if (cause) return `After ${cause}, ${A} began to dream of ${goal}.`;
      return `${A} set ${pronoun} sights on a new dream: ${goal}.`;
    }
    case "town": {
      const eventType = String(event.payload.eventType ?? "something");
      const base = TOWN_EVENT_NARRATION[eventType] ?? `Something happened in ${townName}: ${eventType}.`;
      if (eventType === "fire") {
        const landmark = pickLandmarkFor(seed, "world", event.year, pickLandmarks(seed, townName));
        return `A fire tore through ${landmark}.`;
      }
      return base;
    }
    case "reflection": {
      // A generic kind (round 7, decision 030) for internal, non-relational moments that would
      // otherwise be invisible in the chronicle (it reads the EVENT log, not the decision log) —
      // C2's grief, O2's grudge resolution when the rival is already dead or never forgiven, O4's
      // reckoning with mortality, C3's early calling. `note` picks which; `otherName`, when
      // present, is the other party the reflection concerns.
      const note = String(event.payload.note ?? "");
      const other = typeof event.payload.otherName === "string" ? event.payload.otherName : "them";
      return REFLECTION_NARRATION[note]?.(A, other) ?? `${A} sat with their thoughts.`;
    }
    case "levy":
      return pick(seed, event, [`The lord levied heavily against ${townName}, and ${A} felt it.`, `The lord's collectors came through ${townName} that year, and ${A} paid the price.`]);
    default:
      return `${A}: ${event.kind}.`;
  }
}

/** One prose line per `reflection` note (round 7, decision 030) — a small, closed vocabulary rather than open-ended text, so this stays template-based (decision 001) even though the note itself is a free-ish string tag. */
const REFLECTION_NARRATION: Record<string, (name: string, other: string) => string> = {
  "grieved-openly": (name) => `${name} grieved openly, letting people see it.`,
  hardened: (name) => `${name} hardened themselves and carried on.`,
  "leaned-on-family": (name) => `${name} leaned on what family remained.`,
  "let-go-of-grudge": (name, other) => `${name} finally let go of the old grudge against ${other}, if only within themselves.`,
  "kept-the-grudge": (name, other) => `${name} resolved to take the grudge against ${other} to the grave.`,
  "peace-with-death": (name) => `${name} made peace with the years that were left.`,
  regret: (name) => `${name} dwelled on regrets, with time running short.`,
  "last-wish": (name) => `${name} spoke of one last wish.`,
  "followed-the-family-trade": (name) => `${name} resolved to follow in the family's footsteps.`,
  "sought-an-apprenticeship-elsewhere": (name) => `${name} set out to seek an apprenticeship of their own, away from home.`,
  drifted: (name) => `${name} drifted, not yet sure what to make of themselves.`,
  "competed-with-sibling": (name, other) => `${name} competed with ${other} for attention.`,
  "bonded-with-sibling": (name, other) => `${name} bonded with ${other} instead of competing.`,
  "withdrew-from-sibling": (name) => `${name} withdrew rather than compete for attention at home.`,
  "fought-back-against-bully": (name, other) => `${name} fought back against ${other}.`,
  "endured-the-bully": (name) => `${name} endured the bullying quietly.`,
  "told-an-elder": (name) => `${name} told an elder about the bullying.`,
  "pursued-the-dream-over-trade": (name) => `${name} chose to pursue the dream, whatever it cost the trade.`,
  "stayed-practical": (name) => `${name} set the dream aside and stayed practical.`,
  "opened-up-to-a-friend": (name, other) => `${name} opened up to ${other}, and a real friendship took root.`,
  "kept-their-distance": (name) => `${name} kept a careful distance, and the friendship never quite formed.`,
  "confronted-the-betrayal": (name, other) => `${name} confronted ${other} over the betrayal.`,
  "forgave-the-betrayal": (name, other) => `${name} forgave ${other}, though it was not easily done.`,
  "left-over-the-betrayal": (name, other) => `${name} left ${other} over the betrayal.`,
  "sought-revenge-for-the-betrayal": (name, other) => `${name} sought revenge against ${other}.`,
  "doubled-down-on-faith": (name) => `${name} doubled down on their faith.`,
  "lost-their-faith": (name) => `${name} lost their faith.`,
  "sought-another-path": (name) => `${name} set aside their faith and sought another path.`,
  "resisted-temptation": (name) => `${name} resisted the temptation.`,
  "pursued-an-affair": (name) => `${name} gave in to the temptation.`,
  "took-an-apprentice": (name, other) => `${name} took ${other} on as an apprentice.`,
  "declined-to-mentor": (name) => `${name} declined to take on an apprentice.`,
  "divided-inheritance-eldest": (name) => `${name} left everything to the eldest.`,
  "divided-inheritance-favorite": (name) => `${name} left everything to a favorite.`,
  "split-inheritance": (name) => `${name} split the inheritance evenly.`,
  "inheritance-to-town": (name) => `${name} left the inheritance to the town itself.`,
  "last-attempt-at-dream": (name) => `${name} made one last attempt at the old dream.`,
  "passed-on-dream": (name) => `${name} passed the old dream on to someone else.`,
  "made-peace-with-unrealized-dream": (name) => `${name} made peace with a dream that never came true.`,
  "apprenticed-to-family-trade": (name, other) => `${name} apprenticed ${other} to the family trade.`,
  "sent-away-to-apprentice": (name, other) => `${name} sent ${other} elsewhere to apprentice.`,
  "kept-at-home": (name, other) => `${name} kept ${other} at home a while longer.`,
  "went-on-pilgrimage": (name) => `${name} set out on a pilgrimage.`,
  "stayed-home-from-pilgrimage": (name) => `${name} felt the pull of a pilgrimage, and stayed home all the same.`,
};

/** Third-person narration for a town-level event (round 5, decision 025) — no actors (the event is town-wide), so it doesn't go through the `A`/`B` name substitution the other cases use. */
const TOWN_EVENT_NARRATION: Record<string, string> = {
  plague: "A plague swept through town.",
  famine: "A famine struck the town.",
  fire: "A fire tore through part of town.",
  festival: "The town held a festival.",
  conflict: "A conflict broke out with a neighboring town.",
  harvest: "A bountiful harvest blessed the town.",
  stranger: "A traveling stranger arrived in town.",
};

/** Adjective form of an emotion, for DF-style "felt X upon Y" sentences. */
const EMOTION_ADJECTIVE: Record<string, string> = {
  joy: "joyful",
  pride: "proud",
  love: "smitten",
  hope: "hopeful",
  relief: "relieved",
  contentment: "content",
  grief: "grief-stricken",
  anger: "furious",
  bitterness: "bitter",
  fear: "afraid",
  shame: "ashamed",
  loneliness: "lonely",
  despair: "despairing",
  betrayal: "betrayed",
  jealousy: "jealous",
  regret: "regretful",
};

/**
 * DF-style thought sentences: "felt bitter upon being passed over for
 * miller." A thought whose cause references an earlier memory (matched by
 * `personId` + emotion) is rendered as a revisit: "…felt bitter
 * remembering…" — the past resurfacing, not a fresh event.
 */
export function narrateThought(name: string, thought: Thought, mind: PersonMind): string {
  const adjective = EMOTION_ADJECTIVE[thought.emotion] ?? thought.emotion;
  const isRevisit = mind.memories.some((m) => m.personId === thought.personId && m.emotion === thought.emotion && m.year < thought.year);
  if (isRevisit) {
    const memory = mind.memories.find((m) => m.personId === thought.personId && m.emotion === thought.emotion)!;
    return `${name} felt ${adjective} remembering ${thought.cause}, back in ${memory.year}.`;
  }
  return `${name} felt ${adjective} upon ${thought.cause}.`;
}

/** Memories and grudges surfaced for the biography — core memories first (the ones that actually shaped the person, per decision 007/mind-model.md step 4). */
// Memory `text` is always written with its own year already embedded (e.g. "clashed with X in 1533" —
// see the memory-writing call sites in simulate.ts), so the sentence wrapper here must NOT restate the
// year itself, or it reads as "…from 1533: clashed with X in 1533."
export function narrateMemory(name: string, memory: Memory): string {
  if (memory.emotion === "betrayal" || memory.emotion === "bitterness") {
    return memory.personId ? `${name} has never forgiven them: ${memory.text}` : `${name} still carries a grudge: ${memory.text}`;
  }
  return `${name} still remembers: ${memory.text}`;
}

export interface NarratedEvent {
  readonly event: Event;
  readonly prose: string;
  readonly significance: number;
  /** A short (3-8 word), title-cased version for a Living Chronicle-style entry heading (round 5 pivot, decision 026) — see `RenderedEvent`. */
  readonly title: string;
}

/** `{ title, prose }` — exactly the shape docs/design/handoff.md's `LifeEvent` wants: a short heading plus the full sentence, both from ONE specific person's point of view. */
export interface RenderedEvent {
  readonly title: string;
  readonly prose: string;
}

export type FamilyRelation = "husband" | "wife" | "mother" | "father" | "son" | "daughter";

/** How `other` relates to `viewer` — spouse, parent or child — or `undefined` if they're not immediate family. Used so a chronicle reads "Her husband Merric died" rather than just "Merric died" on the surviving spouse's own page. Exported for the person-rail UI (round 6), which needs the same relation labels. */
export function familyRelation(viewer: Person, other: Person): FamilyRelation | undefined {
  if (other.id === viewer.spouseId) return other.sex === "m" ? "husband" : "wife";
  if (other.id === viewer.motherId) return "mother";
  if (other.id === viewer.fatherId) return "father";
  if (viewer.id === other.motherId || viewer.id === other.fatherId) return other.sex === "m" ? "son" : "daughter";
  return undefined;
}

function possessive(sex: Person["sex"]): "Her" | "His" {
  return sex === "f" ? "Her" : "His";
}

function possessiveLower(sex: Person["sex"]): "her" | "his" {
  return sex === "f" ? "her" : "his";
}

function subjectPronoun(sex: Person["sex"]): "she" | "he" {
  return sex === "f" ? "she" : "he";
}

function objectPronoun(sex: Person["sex"]): "her" | "him" {
  return sex === "f" ? "her" : "him";
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

/**
 * "a" or "an" for a noun — round 8 fix (decision 033, "Becomes a innkeeper"). A plain
 * vowel-letter check is enough for the app's closed, known vocabulary (job names); it isn't a
 * general English article rule (e.g. "a university"), but nothing in `JOB_POOL` or elsewhere this
 * is used needs that.
 */
export function article(noun: string): "a" | "an" {
  return /^[aeiou]/i.test(noun) ? "an" : "a";
}

/** "a/an {noun}" in one call — the common case at every call site below. */
function withArticle(noun: string): string {
  return `${article(noun)} ${noun}`;
}

/**
 * A short title for one event, from `viewerId`'s point of view — e.g. "Her
 * husband dies" rather than "Marries" for someone else's marriage. Covers
 * the kinds a chronicle actually leans on; anything else falls back to a
 * trimmed version of the third-person prose (round 6's Living Chronicle UI
 * is expected to refine titles further — this proves the `{title, prose}`
 * shape works, not final copy for all fifteen event kinds).
 */
function titleFor(event: Event, viewerId: string, people: Readonly<Record<string, Person>>): string {
  const [a, b] = event.actors;
  const viewer = people[viewerId];
  const otherId = a === viewerId ? b : a;
  const other = otherId ? people[otherId] : undefined;
  const relation = viewer && other ? familyRelation(viewer, other) : undefined;

  switch (event.kind) {
    case "birth": {
      if (a === viewerId) return "Is born";
      const child = a ? people[a] : undefined;
      if (child) return `${child.sex === "m" ? "Son" : "Daughter"} ${child.name} is born`;
      return "A child is born";
    }
    case "death": {
      if (a === viewerId) return "Dies";
      if (relation && other) return `${capitalize(relation)} ${other.name} dies`;
      return other ? `${other.name} dies` : "A death in town";
    }
    case "marriage":
      return other ? `Marries ${other.name}` : "Marries";
    case "romance":
      return other ? `Meets ${other.name}` : "Meets someone";
    case "breakup":
      return other ? `Courtship with ${other.name} ends` : "A courtship ends";
    case "feud":
      return event.payload.escalated ? `Feud with ${other?.name ?? "a rival"} deepens` : `Feud breaks out with ${other?.name ?? "a rival"}`;
    case "reconciliation":
      return `Makes peace with ${other?.name ?? "a rival"}`;
    case "job":
      return `Becomes ${withArticle(String(event.payload.job ?? "worker"))}`;
    case "school":
      return "Starts school";
    case "move":
      return event.payload.arrived ? "Arrives in town" : `Leaves for ${String(event.payload.destination ?? "parts unknown")}`;
    case "illness":
      return event.payload.recovered ? "Recovers from illness" : "Falls ill";
    case "child":
      return "Decides to have a child";
    case "breakdown":
      return event.payload.response === "master-it" ? "Overcomes a breaking point" : "Reaches a breaking point";
    case "dream":
      return event.payload.outcome === "realized" ? "A dream realized" : event.payload.outcome === "abandoned" ? "Lets go of a dream" : "Sets a new dream";
    case "town":
      return capitalize(String(event.payload.eventType ?? "something happens"));
    case "reflection": {
      const note = String(event.payload.note ?? "a quiet moment");
      return capitalize(note.replace(/-/g, " "));
    }
    case "levy":
      return "The lord's levy";
    default:
      return capitalize(String(event.kind));
  }
}

/**
 * `{title, prose}` for one event, told from `viewerId`'s perspective — the
 * data shape docs/design/handoff.md's Living Chronicle needs (round 5
 * pivot, decision 026). Prose is `narrateEvent`'s third-person sentence,
 * EXCEPT for a death where the deceased is immediate family of the viewer:
 * that gets a relation-term rewrite ("Her husband Merric died…; she
 * grieved.") instead of just their name, which is what makes every
 * involved person's own chronicle read as being about THEM, not a
 * name-swapped copy of someone else's.
 */
export function narrateEventForViewer(event: Event, viewerId: string, people: Readonly<Record<string, Person>>, seed = "narrate", townName = "town", allEvents: readonly Event[] = []): RenderedEvent {
  const title = titleFor(event, viewerId, people);
  const viewer = people[viewerId];
  const [a] = event.actors;

  if (event.kind === "death" && a !== viewerId && viewer) {
    const deceased = a ? people[a] : undefined;
    const relation = deceased ? familyRelation(viewer, deceased) : undefined;
    if (deceased && relation) {
      const ageStr = typeof event.payload.age === "number" ? `, at age ${event.payload.age}` : "";
      const awayNote = event.payload.awayFromTown ? " (word reached town from afar)" : "";
      const prose = pick(seed, event, [
        `${possessive(viewer.sex)} ${relation} ${deceased.name} died in ${event.year}${ageStr}${awayNote}; ${subjectPronoun(viewer.sex)} grieved.`,
        `${possessive(viewer.sex)} ${relation} ${deceased.name} passed away in ${event.year}${ageStr}${awayNote}, and the loss stayed with ${objectPronoun(viewer.sex)} for years.`,
      ]);
      return { title, prose };
    }
  }

  const prose = narrateEvent(event, people, seed, townName, allEvents);
  return { title, prose: viewer ? prose + innerLifeClause(event, viewer) : prose };
}

/** Event kinds worth an inner-life clause when a matching memory exists — round 6 fix (decision 028, "Ilva's chronicle is a list of facts"). Left off the quieter kinds (school, job, illness-recovered) so it doesn't read as an emotional reaction to everything. */
const INNER_LIFE_KINDS: ReadonlySet<Event["kind"]> = new Set(["dream", "breakdown", "feud", "reconciliation", "marriage", "breakup", "child"]);

/**
 * Weaves the person's own mind into a chronicle entry — "…; she felt proud. This would stay with
 * her for years." — by matching the event's year against a memory `addMemory` already wrote at
 * that exact year (simulate.ts writes one for every major outcome). Deterministic and
 * event-backed: never invents a feeling the mind state doesn't already record.
 */
function innerLifeClause(event: Event, viewer: Person): string {
  if (!INNER_LIFE_KINDS.has(event.kind)) return "";
  const memory = viewer.mind.memories.find((m) => m.year === event.year);
  if (!memory) return "";
  const adjective = EMOTION_ADJECTIVE[memory.emotion] ?? memory.emotion;
  const durability = memory.core ? ` This would stay with ${objectPronoun(viewer.sex)} for years.` : "";
  return ` ${capitalize(subjectPronoun(viewer.sex))} felt ${adjective}.${durability}`;
}

/**
 * A deterministic, template-built one-paragraph ending summary — the
 * handoff's "Mara Ashwell died at sixty in Ravenford, surrounded by her
 * children" line. Built entirely from real fields (job, dream status,
 * whether they ever left town for good, living children, cause of death),
 * never generated text (decision 001).
 */
export function lifeSummary(person: Person, people: Readonly<Record<string, Person>>, events: readonly Event[], townName: string): string {
  const name = person.name;
  const pronounPossessive = person.sex === "f" ? "her" : "his";
  const subject = subjectPronoun(person.sex);

  if (person.deathYear === undefined) {
    const jobClause = person.job !== "none" ? ` ${capitalize(subject)} works as ${withArticle(person.job)}.` : "";
    return `${name} is still living, in ${townName}.${jobClause}`;
  }

  const age = person.deathYear - person.birthYear;
  const awayFromTown = hasMovedAway(events, person.id);
  const placeClause = awayFromTown ? "far from home" : `in ${townName}`;
  const livingChildren = Object.values(people).filter((c) => (c.motherId === person.id || c.fatherId === person.id) && c.deathYear === undefined);
  // "Surrounded by" only makes sense when the children are plausibly WITH her — someone who died
  // away from town almost certainly didn't have her Ashford-based children at her side (round 5
  // fix: the screenshot review caught "died... surrounded by her children far from home", which
  // doesn't logically follow — "survived by" makes the same factual claim without implying presence).
  const survivedClause = livingChildren.length > 0 ? `, ${awayFromTown ? "survived by" : "surrounded by"} ${pronounPossessive} ${livingChildren.length === 1 ? "child" : "children"}` : "";
  const jobClause = person.job !== "none" ? ` ${capitalize(subject)} spent much of ${pronounPossessive} life as ${withArticle(person.job)}.` : "";
  const leftClause = awayFromTown ? ` ${capitalize(subject)} left ${townName} behind and never returned.` : ` ${capitalize(subject)} never permanently left the town where ${subject} was born.`;
  const goal = dreamGerund(person.mind.dream.goal);
  const dreamClause =
    person.mind.dream.status === "realized"
      ? ` ${pronounPossessive === "her" ? "Her" : "His"} dream of ${goal} came true.`
      : person.mind.dream.status === "abandoned"
        ? ` ${pronounPossessive === "her" ? "Her" : "His"} dream of ${goal} was let go along the way.`
        : ` ${pronounPossessive === "her" ? "Her" : "His"} dream of ${goal} never came to pass.`;

  return `${name} died at ${age}${survivedClause} ${placeClause}.${jobClause}${leftClause}${dreamClause}`;
}

const DEFAULT_SIGNIFICANCE: Record<Event["kind"], number> = {
  birth: 0.7,
  school: 0.15,
  job: 0.35,
  move: 0.55,
  romance: 0.5,
  marriage: 0.85,
  breakup: 0.6,
  feud: 0.55,
  reconciliation: 0.5,
  illness: 0.25,
  death: 1,
  child: 0.4,
  breakdown: 0.65,
  dream: 0.6,
  town: 0.7,
  reflection: 0.45,
  levy: 0.6,
};

/**
 * Narrates one person's timeline and scores each event's narrative
 * significance for "story sifting" (highlighting key moments). Significance
 * is computed only for the displayed person's events — bounding the number
 * of extra AI calls this triggers, per the significance budget note in the
 * design brief.
 *
 * Two kinds of events are deliberately left out of the rendered timeline,
 * though they remain in the raw event log and are still walkable through
 * `causes[]`:
 *  - `child` events (the decision to conceive) are folded into the `birth`
 *    event that follows the same year — showing both is redundant ("X and Y
 *    decided to have a child" immediately followed by "Z was born to X and
 *    Y").
 *  - `illness` events that are cited as the cause of a death in the same
 *    log are folded into that death's narration instead of shown as a
 *    separate line.
 */
export async function narratePersonTimeline(
  personId: string,
  events: readonly Event[],
  people: Readonly<Record<string, Person>>,
  decisionMaker?: DecisionMaker,
  concurrencyLimit = 8,
  seed = "narrate",
  townName = "town",
): Promise<NarratedEvent[]> {
  const subsumedIllnesses = illnessIdsSubsumedByDeath(events);
  const personEvents = events
    .filter((e) => e.actors.includes(personId))
    .filter((e) => e.kind !== "child")
    .filter((e) => !(e.kind === "illness" && subsumedIllnesses.has(e.id)))
    .sort((a, b) => a.year - b.year);

  const scored = await mapWithConcurrency(personEvents, concurrencyLimit, async (event) => {
    const { title, prose } = narrateEventForViewer(event, personId, people, seed, townName, events);
    // A forced event (the edit itself) is always the pivotal moment of that branch's story.
    if (event.payload.forced) return { event, prose, title, significance: 1 };
    if (event.significance !== undefined) return { event, prose, title, significance: event.significance };
    if (decisionMaker?.significance) {
      try {
        const significance = await decisionMaker.significance({ summary: prose, state: { kind: event.kind, year: event.year, payload: event.payload } });
        return { event, prose, title, significance };
      } catch {
        // Fall through to the heuristic on any adapter failure; narration must never hard-fail a page render.
      }
    }
    return { event, prose, title, significance: DEFAULT_SIGNIFICANCE[event.kind] };
  });

  return scored;
}
